models/alert.py
import uuid
from typing import Dict
from dataclasses import dataclass, field
from models.item import Item
from models.model import Model
from models.user import User
from libs.mailgun import Mailgun

@dataclass(eq=False)
class Alert(Model):
    collection: str = field(init=False, default="alerts")
    name: str
    item_id: str
    price_limit: float
    user_email: str
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def __post_init__(self):
        self.item = Item.get_by_id(self.item_id)
        self.user = User.find_by_email(self.user_email)
      
    def json(self) -> Dict:
        return {
            "_id": self._id,
            "name": self.name,
            "item_id": self.item_id,
            "price_limit": self.price_limit,
            "user_email": self.user_email
        }

    def load_item_price(self) -> float:
        self.item.load_price()
        return self.item.price

    def notify_if_price_reached(self) -> None:
        "send email"
        if self.item.price < self.price_limit:
            print(f"item {self.item} has reached a price under {self.price_limit}. Latest price: {self.item.price}.")
            Mailgun.send_email(
                email=[self.user_email],
                subject=f"Notification for {self.name}",
                text=f"Your alert {self.name} has reached a price under {self.price_limit}. The latest price is {self.item.price}. Go to this address to check your item: {self.item.url}.",
                html=f'<p>Your alert {self.name} has reached a price under {self.price_limit}.</p><p>The latest price is {self.item.price}. Check your item out <a href="{self.item.url}>here</a>.</p>',
            )

views/alerts.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from models.alert import Alert
from models.item import Item
from models.store import Store, StoreErrors
from models.user import requires_login

alert_blueprint = Blueprint("alerts", __name__)

@alert_blueprint.route("/")
@requires_login
def index():
    alerts = Alert.find_many_by("user_email", session["email"])
    return render_template("alerts/index.html", alerts=alerts)

@alert_blueprint.route("/new", methods=["GET", "POST"])
@requires_login
def new_alert():
    if request.method == "POST":
        alert_name = request.form["name"]
        item_url = request.form["item_url"]
        price_limit = float(request.form["price_limit"])
        # store = Store.find_by_url(item_url)
        # item = Item(item_url, store.tag_name, store.query)
        # item.load_price()
        # item.save_to_mongo()


        # Alert(alert_name, item._id, price_limit, session["email"]).save_to_mongo()
        try:
            store = Store.find_by_url(item_url)
            item = Item(item_url, store.tag_name, store.query)
            item.load_price()
            item.save_to_mongo()
            Alert(alert_name, item._id, price_limit, session["email"]).save_to_mongo()
        except StoreErrors.StoreNotFound as error:
            return render_template("alerts/error.html", error=error)

    return render_template("alerts/new_alert.html")


@alert_blueprint.route("/edit/<string:alert_id>", methods=["GET", "POST"])
@requires_login
def edit_alert(alert_id):
    alert = Alert.get_by_id(alert_id)

    if request.method == "POST":
        price_limit = float(request.form["price_limit"])

        alert.price_limit = price_limit # modify
        alert.save_to_mongo()

        return redirect(url_for(".index"))
    return render_template("alerts/edit_alert.html", alert=alert)

@alert_blueprint.route("/delete/<string:alert_id>")
@requires_login
def delete_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    if alert.user_email == session["email"]:
        alert.remove_from_mongo()
    return redirect(url_for(".index"))

templates/alerts/edit_alert.html
{% extends "base.html" %}

{% block content %}
<header><h1 style="font-weight: bold">Update Alert</h1></header>
<section class="update-alert-form">
    <form method="post">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ alert.name }}" disabled />
        </div>
        <div class="form-group">
            <label for="item_url">Item URL</label>
            <input type="text" class="form-control" id="item_url" name="item_url" value="{{ alert.item.url }}" disabled/>
        </div>
        <div class="form-group">
            <label for="price_limit">Price limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" value="{{ alert.price_limit }}" placeholder="100" aria-describedby="priceLimitHelp"/>
            <small class="form-text text-muted" id="priceLimitHelp">
                Under which price for the item would you like to get notified?
            </small>
        </div>
        <button type="submit" class="btn btn-outline-dark">Update</button>
    </form>
</section>
{% endblock %}

templates/alerts/error.html
{% extends "base.html" %}

{% block content %}
<div class="alert alert-danger" role="alert">
    {{ error.message }}
</div>
{% endblock %}

templates/alerts/index.html
{% extends "base.html" %}

{% block content %}
<header>
    <h1 style="font-weight: bold">Alerts</h1>
</header>
<section>
    <div class="list-group mb-3">
        {% for alert in alerts %}
            <div class="list-group-item">
                <h4>{{ alert.name }}</h4>
                <p>
                    <a href="{{ alert.item.url }}" target="_blank">{{ alert.item_id }} (Last price ${{ alert.item.price }})</a>
                </p>
                <a class="btn btn-secondary" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}">Edit</a>
                <a class="btn btn-danger" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}">Delete</a>
            </div>

        {% endfor %}
    </div>
    <a class="btn btn-outline-dark" href="{{ url_for('alerts.new_alert')}}">
        Create new 
    </a>
</section>
{% endblock %}

templates/alerts/new_alert.html
{% extends "base.html" %}

{% block content %}
<header><h1 style="font-weight: bold">Create Alert</h1></header>
<section class="create-alert-form">
    <form method="post">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" required='required'/>
        </div>
        <div class="form-group">
            <label for="item_url">Item URL</label>
            <input type="text" class="form-control" id="item_url" name="item_url" required='required'/>
        </div>
        <div class="form-group">
            <label for="price_limit">Price limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="100" aria-describedby="priceLimitHelp" required='required'/>
            <small class="form-text text-muted" id="priceLimitHelp">
                Under which price for the item would you like to get notified?
            </small>
        </div>
        <button type="submit" class="btn btn-success">Create</button>
    </form>
    <a href="{{ url_for('alerts.new_alert') }}"><button type="submit" class="btn btn-warning mt-3">Cancel</button></a>
</section>
{% endblock %}