models/store/__init__.py
from models.store.store import Store
import models.store.errors as StoreErrors

views/stores.py
import json
from flask import Blueprint, render_template, request, url_for, redirect
from models.store import Store
from models.user import requires_admin, requires_login

store_blueprint = Blueprint("stores", __name__)


@store_blueprint.route("/")
@requires_login
def index():
    stores = Store.all()
    return render_template("stores/index.html", stores=stores)

@store_blueprint.route("/new", methods=["GET", "POST"])
@requires_admin
def create_store():
    if request.method == "POST":
        name = request.form["name"]
        url_prefix = request.form["url_prefix"]
        tag_name = request.form["tag_name"]
        query = json.loads(request.form["query"])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

    return render_template("stores/new_store.html")
    
@store_blueprint.route("/edit/<string:store_id>", methods=["GET", "POST"])
@requires_admin
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if request.method == "POST":
        name = request.form["name"]
        url_prefix = request.form["url_prefix"]
        tag_name = request.form["tag_name"]
        query = json.loads(request.form["query"])

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()
        return redirect(url_for(".index"))
    store_query = json.dumps(store.query) # display double quote format 
    return render_template("stores/edit_store.html", store=store, store_query=store_query)

@store_blueprint.route("/detete/<string:store_id>")
@requires_admin
def delete_store(store_id):
    Store.get_by_id(store_id).remove_from_mongo()
    return redirect(url_for(".index"))

templates/stores/edit_store.html
{% extends "base.html" %}

{% block content %}
<header><h1 style="font-weight: bold">Edit Store</h1></header>
<section class="create-alert-form">
    <form method="post">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Amozon" value="{{ store.name }}" />
        </div>
        <div class="form-group">
            <label for="url_prefix">URL Prefix</label>
            <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="https://..." value="{{ store.url_prefix }}" aria-describedby="urlPrefixHelp"/>
            <small class="form-text text-muted" id="urlPrefixHelp">
                What URL will all its items start with?
            </small>
        </div>
        <div class="form-group">
            <label for="tag_name">HTML Tag Name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="{{ store.tag_name }}" aria-describedby="tagNameHelp" />
            <small class="form-text text-muted" id="tagNameHelp">
                What HTML tag contains the price information for items in this store?
            </small>
        </div>
        <div class="form-group">
            <label for="query">HTML Query</label>
            <input type="text" class="form-control" id="query" name="query" placeholder='{"class": "price price--large"}' value="{{ store_query }}" aria-describedby="queryHelp"/>
            <small class="form-text text-muted" id="queryHelp">
                What attributes are on the element that contain the price? This is can find it on the page.
            </small>
        </div>
       
        <button type="submit" class="btn btn-outline-dark">Update</button>
    </form>
</section>
{% endblock %}

templates/stores/index.html
{% extends "base.html" %}

{% block content %}
<header>
    <h1 style="font-weight: bold">Stores</h1>
    <p style="color:gray">Supported online stores</p>
</header>
<section>
    <div class="list-group mb-3">
        {% for store in stores %}
        <div class="list-group-item">
            <h4>{{ store.name }}</h4>
            <p>
                For URL starting with <strong>{{ store.url_prefix }}</strong>
            </p>
            {% if session["email"] == config.ADMIN %}
            <a class="btn btn-secondary" href="{{ url_for('stores.edit_store', store_id=store._id) }}">Edit</a>
            <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}">Delete</a>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    {% if session["email"] == config.ADMIN %}
    <a class="btn btn-outline-dark" href="{{ url_for('stores.create_store')}}">Create new </a>
    {% endif %}
</section>
{% endblock %}

templates/stores/new_store.html
{% extends "base.html" %}

{% block content %}
<header><h1 style="font-weight: bold">Create Store</h1></header>
<section class="create-alert-form">
    <form method="post">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Keds"/>
        </div>
        <div class="form-group">
            <label for="url_prefix">URL Prefix</label>
            <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="https://..." aria-describedby="urlPrefixHelp"/>
            <small class="form-text text-muted" id="urlPrefixHelp">
                What URL will all its items start with?
            </small>
        </div>
        <div class="form-group">
            <label for="tag_name">HTML Tag Name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" aria-describedby="tagNameHelp" />
            <small class="form-text text-muted" id="tagNameHelp">
                What HTML tag contains the price information for items in this store?
            </small>
        </div>
        <div class="form-group">
            <label for="query">HTML Query</label>
            <input type="text" class="form-control" id="query" name="query" placeholder='{"class": "price price--large"}' aria-describedby="queryHelp"/>
            <small class="form-text text-muted" id="queryHelp">
                What attributes are on the element that contain the price? This is can find it on the page.
            </small>
        </div>
       
        <button type="submit" class="btn btn-outline-dark">Create</button>
    </form>
</section>
{% endblock %}