views/stores.py
import json
from flask import Blueprint, render_template, request, url_for, redirect
from models.store import Store
from models.user import requires_admin, requires_login

store_blueprint = Blueprint("stores", __name__)


@store_blueprint.route("/")
@requires_login
def index():
    stores = Store.all()
    return render_template("stores/index.html", stores=stores)

@store_blueprint.route("/new", methods=["GET", "POST"])
@requires_admin
def create_store():
    if request.method == "POST":
        name = request.form["name"]
        url_prefix = request.form["url_prefix"]
        tag_name = request.form["tag_name"]
        query = json.loads(request.form["query"])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

    return render_template("stores/new_store.html")
    
@store_blueprint.route("/edit/<string:store_id>", methods=["GET", "POST"])
@requires_admin
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if request.method == "POST":
        name = request.form["name"]
        url_prefix = request.form["url_prefix"]
        tag_name = request.form["tag_name"]
        query = json.loads(request.form["query"])

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()
        return redirect(url_for(".index"))
    store_query = json.dumps(store.query) # display double quote format 
    return render_template("stores/edit_store.html", store=store, store_query=store_query)

@store_blueprint.route("/detete/<string:store_id>")
@requires_admin
def delete_store(store_id):
    Store.get_by_id(store_id).remove_from_mongo()
    return redirect(url_for(".index"))

views/users.py
from flask import Blueprint, render_template, session, url_for, redirect, request
from models.user import User, UserErrors


user_blueprint = Blueprint("users", __name__)

@user_blueprint.route("/register", methods=["GET", "POST"])
def register_user():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]

        try:
            User.register_user(email, password)
            session["email"] = email
            return redirect(url_for('alerts.index'))
        except UserErrors.UserError as error:
            return render_template("users/error.html", error=error)

    return render_template("users/register.html")


@user_blueprint.route("/login", methods=["GET", "POST"])
def login_user():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]

        try:
            if User.is_login_valid(email, password):
                session["email"] = email
                return redirect(url_for('alerts.index'))
        except UserErrors.UserError as error:
            return render_template("users/error.html", error=error)
    return render_template("users/login.html")

@user_blueprint.route("/logout")
def logout():
    session["email"] = None
    return redirect(url_for(".login_user"))

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Pricing Alert Service</title>
  </head>
  <body>
    <div class="content container mt-2">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
            <img src="{{url_for('static', filename='claire blog logo_b.png')}}" height="30" class="d-inline-block align-top mr-2">
            <a class="navbar-brand" href="{{ url_for('home') }}" style="font-weight: bold">Pricing Alert Service</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link {% if request.path == '/stores/' %} active {% endif %}" href="{{ url_for('stores.index') }}" style="font-weight: bold">Stores</a>
                    <a class="nav-item nav-link {% if request.path == '/alerts/' %} active {% endif %}" href="{{ url_for('alerts.index') }}" style="font-weight: bold">Alerts</a>
                    {% if session["email"] %}
                    <a class="nav-item nav-link {% if request.path == '/users/logout' %} active {% endif %}" href="{{ url_for('users.logout') }}" style="font-weight: bold">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link {% if request.path == '/users/login' %} active {% endif %}" href="{{ url_for('users.login_user') }}"style="font-weight: bold">Login</a>
                    {% endif %}
                    <a class="nav-item nav-link {% if request.path == '/users/register' %} active {% endif %}" href="{{ url_for('users.register_user') }}"style="font-weight: bold">Register</a>
                </div>
            </div>
        </nav>
        {% with messages = get_flashed_messages(with_categories=true) %} 
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{category}}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

        {% endwith %}
        <div class="mt-3">
        {% block content %}

        {% endblock %}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4" style="font-weight: bold">Pricing Alert Service</h1>
        <p class="lead">We scan online store websites and alert you of price drop in items that you are insterested.</p>
        <hr class="my-4" />
        <p>Just Sign up and provide the URL of items that you wish to track.</p>
        <a class="btn btn-warning btn-lg" href="{{ url_for('users.register_user') }}">Get Started</a>
    </div>
{% endblock %}